name: Update GNSS Papers

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: pip install -r requirements.txt

      - run: python main.py

      - run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "auto update" || echo "no changes"
          git push
